# configuracion.py

# ESQUELETO
INCREMENTO_ANGULO = 2 # Incremento de ángulo
RADIO_CIRCULO = 0.5 # Radio círculo articulaciones

# PLANO DE PROYECCIÓN
PROJECTION_LEFT = -20
PROJECTION_RIGHT = 20
PROJECTION_BOTTOM = -15
PROJECTION_TOP = 15

# PANTALLA
ANCHO_PANTALLA = 800
ALTO_PANTALLA = 600

# COLORES
COLOR_AZUL = (0.0, 0.0, 1.0)
COLOR_BLANCO = (1.0, 1.0, 1.0)
COLOR_GRIS = (0.5, 0.5, 0.5)
COLOR_MAGENTA = (1.0, 0.0, 1.0)
COLOR_NEGRO = (0.0, 0.0, 0.0)
COLOR_ROJO = (1.0, 0.0, 0.0)
COLOR_VERDE = (0.0, 1.0, 0.0)
COLOR_ARTICULACION_NO_SELECCIONADA = COLOR_AZUL
COLOR_ARTICULACION_SELECCIONADA = COLOR_ROJO
COLOR_RAIZ = COLOR_NEGRO

# BUCLE DE RENDERIZADO
FPS = 60