# configuracion_esqueleto.py

###############################
#        BRAZO DERECHO        #
###############################

#Limites de movimiento del hombro derecho
ANGULO_MIN_HOMBRO_DERECHO = -90
ANGULO_MAX_HOMBRO_DERECHO = 90
#Limites de movimiento del codo derecho
ANGULO_MIN_CODO_DERECHO = -135
ANGULO_MAX_CODO_DERECHO = 0
#Limites de movimiento de la muñeca derecha
ANGULO_MIN_MUNECA_DERECHA = -45
ANGULO_MAX_MUNECA_DERECHA = 45

#Angulos iniciales
ANGULO_INICIAL_HOMBRO_DERECHO = -90
ANGULO_INICIAL_CODO_DERECHO = 0
ANGULO_INICIAL_MUNECA_DERECHA = 0

###############################
#       BRAZO IZQUIERDO       #
###############################

# Límites
# Límites de movimiento del hombro izquierdo
ANGULO_MIN_HOMBRO_IZQUIERDO = -90
ANGULO_MAX_HOMBRO_IZQUIERDO = 90
# Límites de movimiento del codo izquierdo
ANGULO_MIN_CODO_IZQUIERDO = 0
ANGULO_MAX_CODO_IZQUIERDO = 135
# Límites de movimiento de la muñeca izquierda
ANGULO_MIN_MUNECA_IZQUIERDA = -45
ANGULO_MAX_MUNECA_IZQUIERDA = 45

# Ángulos iniciales
ANGULO_INICIAL_HOMBRO_IZQUIERDO = 90
ANGULO_INICIAL_CODO_IZQUIERDO = 0
ANGULO_INICIAL_MUNECA_IZQUIERDA = 0

###############################
#        PIERNA DERECHA       #
###############################

# Límites
ANGULO_MIN_CADERA_DERECHA = -180 # TODO: EJERCICIO 3
ANGULO_MAX_CADERA_DERECHA = 180 # TODO: EJERCICIO 3
ANGULO_MIN_RODILLA_DERECHA = -180 # TODO: EJERCICIO 3
ANGULO_MAX_RODILLA_DERECHA = 180 # TODO: EJERCICIO 3
ANGULO_MIN_TOBILLO_DERECHO = -180 # TODO: EJERCICIO 3
ANGULO_MAX_TOBILLO_DERECHO = 180 # TODO: EJERCICIO 3

# Ángulos iniciales
ANGULO_INICIAL_CADERA_DERECHA = 0 # TODO: EJERCICIO 3
ANGULO_INICIAL_RODILLA_DERECHA = 0 # TODO: EJERCICIO 3
ANGULO_INICIAL_TOBILLO_DERECHO = 0 # TODO: EJERCICIO 3

###############################
#       PIERNA IZQUIERDA      #
###############################

# Límites
ANGULO_MIN_CADERA_IZQUIERDA = -180 # TODO: EJERCICIO 4
ANGULO_MAX_CADERA_IZQUIERDA = 180 # TODO: EJERCICIO 4
ANGULO_MIN_RODILLA_IZQUIERDA = -180 # TODO: EJERCICIO 4
ANGULO_MAX_RODILLA_IZQUIERDA = 180 # TODO: EJERCICIO 4
ANGULO_MIN_TOBILLO_IZQUIERDO = -180 # TODO: EJERCICIO 4
ANGULO_MAX_TOBILLO_IZQUIERDO = 180 # TODO: EJERCICIO 4

# Ángulos iniciales
ANGULO_INICIAL_CADERA_IZQUIERDA = 0 # TODO: EJERCICIO 4
ANGULO_INICIAL_RODILLA_IZQUIERDA = 0 # TODO: EJERCICIO 4
ANGULO_INICIAL_TOBILLO_IZQUIERDO = 0 # TODO: EJERCICIO 4